import { ExamType, Subject } from '../types';

export const EXAM_TYPES: ExamType[] = ['JEE Mains', 'JEE Advanced', 'NEET', 'CBSE'];

export const SUBJECTS_BY_EXAM: Record<ExamType, Subject[]> = {
  'JEE Mains': ['Physics', 'Chemistry', 'Mathematics'],
  'JEE Advanced': ['Physics', 'Chemistry', 'Mathematics'],
  NEET: ['Physics', 'Chemistry', 'Biology'],
  CBSE: ['Physics', 'Chemistry', 'Mathematics', 'Biology'],
};

export const CHAPTERS: Record<Subject, string[]> = {
  Physics: [
    'Units & Measurements',
    'Motion in a Straight Line',
    'Motion in a Plane',
    'Laws of Motion',
    'Work, Energy & Power',
    'System of Particles & Rotational Motion',
    'Gravitation',
    'Mechanical Properties of Solids',
    'Mechanical Properties of Fluids',
    'Thermal Properties of Matter',
    'Thermodynamics',
    'Kinetic Theory',
    'Oscillations',
    'Waves',
    'Electric Charges & Fields',
    'Electrostatic Potential & Capacitance',
    'Current Electricity',
    'Moving Charges & Magnetism',
    'Magnetism & Matter',
    'Electromagnetic Induction',
    'Alternating Current',
    'Electromagnetic Waves',
    'Ray Optics',
    'Wave Optics',
    'Dual Nature of Radiation & Matter',
    'Atoms',
    'Nuclei',
    'Semiconductor Electronics',
  ],
  Chemistry: [
    'Some Basic Concepts of Chemistry',
    'Structure of Atom',
    'Classification of Elements',
    'Chemical Bonding',
    'States of Matter',
    'Thermodynamics',
    'Equilibrium',
    'Redox Reactions',
    'Hydrogen',
    's-Block Elements',
    'p-Block Elements',
    'd & f-Block Elements',
    'Coordination Compounds',
    'Organic Chemistry: Basic Principles',
    'Hydrocarbons',
    'Haloalkanes & Haloarenes',
    'Alcohols, Phenols & Ethers',
    'Aldehydes, Ketones & Carboxylic Acids',
    'Amines',
    'Biomolecules',
    'Polymers',
    'Chemistry in Everyday Life',
    'Electrochemistry',
    'Chemical Kinetics',
    'Surface Chemistry',
  ],
  Mathematics: [
    'Sets',
    'Relations & Functions',
    'Trigonometric Functions',
    'Principle of Mathematical Induction',
    'Complex Numbers',
    'Linear Inequalities',
    'Permutations & Combinations',
    'Binomial Theorem',
    'Sequences & Series',
    'Straight Lines',
    'Conic Sections',
    'Introduction to 3D Geometry',
    'Limits & Derivatives',
    'Statistics',
    'Probability',
    'Matrices',
    'Determinants',
    'Continuity & Differentiability',
    'Applications of Derivatives',
    'Integrals',
    'Applications of Integrals',
    'Differential Equations',
    'Vector Algebra',
    'Three-Dimensional Geometry',
    'Linear Programming',
  ],
  Biology: [
    'The Living World',
    'Biological Classification',
    'Plant Kingdom',
    'Animal Kingdom',
    'Morphology of Flowering Plants',
    'Anatomy of Flowering Plants',
    'Structural Organisation in Animals',
    'Cell: The Unit of Life',
    'Biomolecules',
    'Cell Cycle & Cell Division',
    'Transport in Plants',
    'Mineral Nutrition',
    'Photosynthesis',
    'Respiration in Plants',
    'Plant Growth & Development',
    'Digestion & Absorption',
    'Breathing & Exchange of Gases',
    'Body Fluids & Circulation',
    'Excretory Products & Elimination',
    'Locomotion & Movement',
    'Neural Control & Coordination',
    'Chemical Coordination',
    'Reproduction in Organisms',
    'Sexual Reproduction in Flowering Plants',
    'Human Reproduction',
    'Genetics & Evolution',
    'Molecular Basis of Inheritance',
    'Evolution',
    'Human Health & Disease',
    'Ecosystem',
    'Biodiversity',
    'Environmental Issues',
  ],
};

export const DIFFICULTIES = ['Easy', 'Medium', 'Hard', 'Previous Year'] as const;

export const QUESTION_TYPES = [
  'MCQ',
  'Assertion-Reason',
  'Match the Column',
  'Integer Type',
  'Short Answer',
] as const;

export const QUESTION_COUNTS = [5, 10, 15, 20, 30, 50];

export const FREE_TIER_LIMITS = {
  dailyGenerations: 5,
  weeklyPracticeTests: 2,
};
